apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-deployment
  labels:
    app: eureka-deployment
spec:
  selector:
    matchLabels:
      app: eureka-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: eureka-deployment
    spec:
      containers:
        - name: eureka-server
          image: diegomuu/eureka-server
          ports:
            - containerPort: 8761
          env:
            - name: SPRING_CONFIG_IMPORT
              value: "optional:configserver:http://config-server-service:8888"
---
apiVersion: v1
kind: Service
metadata:
  name: eureka-server
  labels:
    app: eureka-server
spec:
  selector:
    app: eureka-deployment
  ports:
    - protocol: TCP
      port: 8761
      targetPort: 8761
  type: LoadBalancer
