apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
  labels:
    app: gateway-deployment
spec:
  selector:
    matchLabels:
      app: gateway-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: gateway-deployment
    spec:
      containers:
        - name: gateway
          image: diegomuu/gateway
          ports:
            - containerPort: 8080
          args:
            - "--eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka/"
          env:
            - name: SERVER_PORT
              value: "8080"
            - name: SPRING_CLOUD_CONFIG_URI
              value: "http://config-server-service:8888"
            - name: SPRING_CLOUD_CONFIG_FAIL_FAST
              value: "true"
            - name: EUREKA_CLIENT_REGISTER_WITH_EUREKA
              value: "true"
            - name: EUREKA_CLIENT_FETCH_REGISTRY
              value: "true"
            - name: EUREKA_INSTANCE_PREFERIPADDRESS
              value: "true"
            - name: EUREKA_INSTANCE_HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: EUREKA_CLIENT_REGISTRY_FETCH_INTERVAL_SECONDS
              value: "5"
            - name: EUREKA_INSTANCE_LEASE_RENEWAL_INTERVAL_IN_SECONDS
              value: "5"
            - name: EUREKA_INSTANCE_LEASE_EXPIRATION_DURATION_IN_SECONDS
              value: "10"
            - name: LOGGING_LEVEL_COM_NETFLIX_DISCOVERY
              value: "DEBUG"
            - name: LOGGING_LEVEL_COM_NETFLIX_EUREKA
              value: "DEBUG"
            - name: SPRING_CLOUD_CONFIG_IMPORT_CHECK_ENABLED
              value: "false"
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  labels:
    app: gateway-service
spec:
  selector:
    app: gateway-deployment
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
