apiVersion: apps/v1
kind: Deployment
metadata:
  name: tarifas-deployment
  labels:
    app: tarifas-deployment
spec:
  selector:
    matchLabels:
      app: tarifas-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: tarifas-deployment
    spec:
      containers:
        - name: tarifas-service
          image: diegomuu/tarifas-service
          ports:
             - containerPort: 8097
          env:
            - name: SERVER_PORT
              value: "0"
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://config-server-service:8888
            - name: SPRING_CLOUD_CONFIG_FAIL_FAST
              value: "true"
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: database-configmap
                  key: tarifas-db-url
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: database-password
            - name: SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT
              value: org.hibernate.dialect.MySQL8Dialect
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: update
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://eureka-server:8761/eureka/
            - name: EUREKA_CLIENT_REGISTER_WITH_EUREKA
              value: "true"
            - name: EUREKA_CLIENT_FETCH_REGISTRY
              value: "true"
            - name: EUREKA_INSTANCE_PREFERIPADDRESS
              value: "true"
            - name: EUREKA_INSTANCE_HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: EUREKA_CLIENT_REGISTRY_FETCH_INTERVAL_SECONDS
              value: "5"
            - name: EUREKA_INSTANCE_LEASE_RENEWAL_INTERVAL_IN_SECONDS
              value: "5"
            - name: EUREKA_INSTANCE_LEASE_EXPIRATION_DURATION_IN_SECONDS
              value: "10"
            - name: LOGGING_LEVEL_COM_NETFLIX_DISCOVERY
              value: "DEBUG"
            - name: LOGGING_LEVEL_COM_NETFLIX_EUREKA
              value: "DEBUG"
            - name: SPRING_CLOUD_CONFIG_IMPORT_CHECK_ENABLED
              value: "false"